var annotated_dup =
[
    [ "Board", "class_board.html", "class_board" ],
    [ "Diamond_AI_Player", "class_diamond___a_i___player.html", "class_diamond___a_i___player" ],
    [ "Diamond_Tic_Tac_Toe_Board", "class_diamond___tic___tac___toe___board.html", "class_diamond___tic___tac___toe___board" ],
    [ "Diamond_Tic_Tac_Toe_UI", "class_diamond___tic___tac___toe___u_i.html", "class_diamond___tic___tac___toe___u_i" ],
    [ "FourInARow_Board", "class_four_in_a_row___board.html", "class_four_in_a_row___board" ],
    [ "FourInARow_UI", "class_four_in_a_row___u_i.html", "class_four_in_a_row___u_i" ],
    [ "GameManager", "class_game_manager.html", "class_game_manager" ],
    [ "Infinity_Board", "class_infinity___board.html", "class_infinity___board" ],
    [ "Infinity_UI", "class_infinity___u_i.html", "class_infinity___u_i" ],
    [ "MemoryTTT_AI_Player", "class_memory_t_t_t___a_i___player.html", null ],
    [ "MemoryTTT_Board", "class_memory_t_t_t___board.html", "class_memory_t_t_t___board" ],
    [ "MemoryTTT_UI", "class_memory_t_t_t___u_i.html", "class_memory_t_t_t___u_i" ],
    [ "MiniBoard", "class_mini_board.html", "class_mini_board" ],
    [ "Misere_Tic_Tac_Toe_Board", "class_misere___tic___tac___toe___board.html", "class_misere___tic___tac___toe___board" ],
    [ "Misere_Tic_Tac_Toe_UI", "class_misere___tic___tac___toe___u_i.html", "class_misere___tic___tac___toe___u_i" ],
    [ "Move", "class_move.html", "class_move" ],
    [ "Numerical_Board", "class_numerical___board.html", "class_numerical___board" ],
    [ "Numerical_UI", "class_numerical___u_i.html", "class_numerical___u_i" ],
    [ "Obstacles_Tic_Tac_Toe_Board", "class_obstacles___tic___tac___toe___board.html", "class_obstacles___tic___tac___toe___board" ],
    [ "Obstacles_Tic_Tac_Toe_UI", "class_obstacles___tic___tac___toe___u_i.html", "class_obstacles___tic___tac___toe___u_i" ],
    [ "Player", "class_player.html", "class_player" ],
    [ "SUS_Board", "class_s_u_s___board.html", "class_s_u_s___board" ],
    [ "SUS_UI", "class_s_u_s___u_i.html", "class_s_u_s___u_i" ],
    [ "Tic_Tac_Toe_4x4_Board", "class_tic___tac___toe__4x4___board.html", "class_tic___tac___toe__4x4___board" ],
    [ "Tic_Tac_Toe_4x4_UI", "class_tic___tac___toe__4x4___u_i.html", "class_tic___tac___toe__4x4___u_i" ],
    [ "TicTacToe5x5", "class_tic_tac_toe5x5.html", "class_tic_tac_toe5x5" ],
    [ "TicTacToe5x5_UI", "class_tic_tac_toe5x5___u_i.html", "class_tic_tac_toe5x5___u_i" ],
    [ "UI", "class_u_i.html", "class_u_i" ],
    [ "UltimateTicTacToe_Board", "class_ultimate_tic_tac_toe___board.html", "class_ultimate_tic_tac_toe___board" ],
    [ "UltimateTicTacToe_UI", "class_ultimate_tic_tac_toe___u_i.html", "class_ultimate_tic_tac_toe___u_i" ],
    [ "WordTicTacToe_Board", "class_word_tic_tac_toe___board.html", "class_word_tic_tac_toe___board" ],
    [ "WordTicTacToe_UI", "class_word_tic_tac_toe___u_i.html", "class_word_tic_tac_toe___u_i" ],
    [ "X_O_Board", "class_x___o___board.html", "class_x___o___board" ],
    [ "XO_UI", "class_x_o___u_i.html", "class_x_o___u_i" ]
];